title: "Cards"
description: |
  Cards are important in this website because they are used on almost every page. They provide the users with lots of details about the pages.

patterns:
    clickable-card:
      title: "Clickable Card"
      padding: 2em
      description: |
        The clickable card is used to show a small thumbnail of each project. Once clicked it will take you to the designated project page.
      fields:
      - name: image
        type: string
        example: "placeholder-1.jpg"
    image-caption-card:
      title: "Image Caption Card"
      description: |
        The image card is used to show a small thumbnail of a project with a caption to explain it briefly.
      fields:
      - name: image
        type: string
        example: "placeholder-1.jpg"
      - name: caption
        type: string
        example: "Explain the image briefly."
      - name: url
        type: url
        example: "/#/"
    image-card:
      title: "Image Card"
      description: |
        The image card is used to show a singular image.
      fields:
      - name: image
        type: string
        example: "placeholder-1.jpg"
