title: "Buttons"
description: |
  These buttons are important for each of the projec tpages so you can navigate through projects easily

patterns:
    next:
      title: "Next Project Button"
      description: |
        This button will be at the bottom of each project page to go to the next project.
      fields:
      - name: url
        type: url
        example: "/#/"
    previous:
      title: "Previous Project Button"
      description: |
        This button will be at the bottom of each project page to go to the previous project.
      fields:
      - name: url
        type: url
        example: "/#/"
