title: "Sections"
description: |
  This website has many sections and each section is different.

patterns:
    card-section:
      title: "Card Section"
      description: |
        The card section is a group of four clickable cards that will be linked to each project page. It is located on the homepage only.
    image-carousel-5:
      title: "Image Carousel"
      description: |
        The image carousel will be used on each project page with 5 images that represent the project. It's purpose is to be put in place of the project card carousel if it doesn't work.
    image-carousel-6:
      title: "Image Carousel 2"
      description: |
        The image carousel will be used on each project page with 6 images that represent the project. It's purpose is to be put in place of the project card carousel if it doesn't work.
    image-text-section:
      title: "Image Text Section"
      description: |
        This section will be used on the about page only. It leaves space for a description and a portrait.
    text-section:
      title: "Text Section"
      description: |
        The text section looks the same as the one featured in the image text section, but this one stands alone. It goes on the homepage.
    project-top-section:
      title: "Project Top Section"
      description: |
        This section will be used at the top of each project page. It shows an image of the project and has a section for the title and the type of work that the project falls under.
    project-card-carousel:
      title: "Project Card Carousel"
      description: |
        This card section will be used on the project page. It is a group of four clickable cards that will be linked to 4 different photos about the project. On clicking the photo should increase to full size.
    project-text-section:
      title: "Project Text Section"
      description: |
        This section will be used on each project page. It's where all text regarding the in-depth project case studies will go.
