title: "Sections"
description: |
  This website has many sections and each section is different.

patterns:
    card-section:
      title: "Card Section"
      padding: 2em
      description: |
        The card section is a group of four clickable cards that will be linked to each project page. It is located on the homepage only.
    image-carousel-4:
      title: "Image Carousel 4"
      description: |
        The image carousel will be used on each project page with 4 images that represent the project. It's purpose is to be put in place of the project card carousel if it doesn't work.
      fields:
      - name: image1
        type: string
        example: "placeholder-1.jpg"
      - name: image2
        type: string
        example: "placeholder-2.jpg"
      - name: image3
        type: string
        example: "placeholder-1.jpg"
      - name: image4
        type: string
        example: "placeholder-2.jpg"
    image-carousel-5:
      title: "Image Carousel 5"
      description: |
        The image carousel will be used on each project page with 5 images that represent the project. It's purpose is to be put in place of the project card carousel if it doesn't work.
      fields:
      - name: image1
        type: string
        example: "placeholder-1.jpg"
      - name: image2
        type: string
        example: "placeholder-2.jpg"
      - name: image3
        type: string
        example: "placeholder-1.jpg"
      - name: image4
        type: string
        example: "placeholder-2.jpg"
      - name: image5
        type: string
        example: "placeholder-1.jpg"
    image-carousel-6:
      title: "Image Carousel 6"
      description: |
        The image carousel will be used on each project page with 6 images that represent the project. It's purpose is to be put in place of the project card carousel if it doesn't work.
      fields:
      - name: image1
        type: string
        example: "placeholder-1.jpg"
      - name: image2
        type: string
        example: "placeholder-2.jpg"
      - name: image3
        type: string
        example: "placeholder-1.jpg"
      - name: image4
        type: string
        example: "placeholder-2.jpg"
      - name: image5
        type: string
        example: "placeholder-1.jpg"
      - name: image6
        type: string
        example: "placeholder-2.jpg"
    text-section-left:
      title: "Image Text Section Left"
      description: |
        This section will be when an image needs to be on the left. It leaves space for a description and a portrait.
      fields:
      - name: image
        type: string
        example: "placeholder-1.jpg"
      - name: title
        type: string
        example: "Title"
      - name: text
        type: string
        example: "Description of project"
    text-section-right:
      title: "Image Text Section Right"
      description: |
        This section will be used when an image needs to be on the right. It leaves space for a description and a portrait.
      fields:
      - name: image
        type: string
        example: "placeholder-1.jpg"
      - name: title
        type: string
        example: "Title"
      - name: text
        type: string
        example: "Description of project"
    text-section:
      title: "Text Section"
      description: |
        The text section looks the same as the one featured in the image text section, but this one stands alone. It goes on the homepage.
      fields:
      - name: title
        type: string
        example: "Title"
      - name: text
        type: string
        example: "Description of project"
    project-top-section:
      title: "Project Top Section"
      description: |
        This section will be used at the top of each project page. It shows an image of the project and has a section for the title and the type of work that the project falls under.
      fields:
      - name: title
        type: string
        example: "Project Title"
      - name: type
        type: string
        example: "Type of project"
      - name: text
        type: string
        example: "Brief Description of project"
      - name: image
        type: string
        example: "placeholder-1.jpg"
    # project-card-carousel:
    #   title: "Project Card Carousel"
    #   description: |
    #     This card section will be used on the project page. It is a group of four clickable cards that will be linked to 4 different photos about the project. On clicking the photo should increase to full size.
    project-text-section:
      title: "Project Text Section"
      description: |
        This section will be used on each project page. It's where all text regarding the in-depth project case studies will go.
      fields:
      - name: sentence1
        type: string
        example: "First sentence"
      - name: sentence2
        type: string
        example: "Second sentence"
      - name: sentence3
        type: string
        example: "Third sentence"
      - name: sentence4
        type: string
        example: "Fourth sentence"
